"""
The Holodeck - Test Configuration
Creates a safe, mock environment for testing the WorldSmith Sidecar agent.
This file is automatically loaded by pytest.
"""

import pytest
import os
from unittest.mock import MagicMock, patch, AsyncMock
import sys

# Ensure source code is accessible
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))


@pytest.fixture
def mock_vault(tmp_path):
    """
    Creates a disposable Vault environment for testing.
    This is the 'Holodeck' - a perfect simulation that costs nothing.
    """
    # 1. Create Folder Structure
    source = tmp_path / "Source Files"
    inbox = tmp_path / "_Agent_Inbox"
    backups = tmp_path / "_backups"

    source.mkdir()
    inbox.mkdir()
    backups.mkdir()

    # 2. Create Dummy Source File (The Input Canon)
    (source / "Tiered Hierarchy.md").write_text(
        "# World Hierarchy\n\n"
        "- Entity: The Iron Dominion\n  Category: 03_Factions\n  Tier: 1\n"
        "- Entity: Forgemaster Kael\n  Category: 05_NPCs\n  Tier: 4\n"
    )

    # 3. Create Sample Canon File
    (source / "Canon_Lore.md").write_text(
        "# The Iron Dominion\n\n"
        "The Breakers forge empires from steel. Efficiency above all.\n"
        "[[Forgemaster Kael]] leads the operations."
    )

    # 4. Point ENV vars to this temp folder
    with patch.dict(
        os.environ,
        {
            "VAULT_ROOT": str(tmp_path),
            "SOURCE_ROOT": str(source),
            "INBOX_DIR": str(inbox),
            "MAX_RECURSION": "10",
            "GM_MODE": "True",
            "BACKUP_MODE": "True",
            "GOOGLE_API_KEY": "dummy_key",
        },
    ):
        yield tmp_path


@pytest.fixture
def mock_llm():
    """
    Mocks Google Gemini to return predictable, FREE responses.
    No API calls = No costs = Fast tests.
    """
    with patch("src.core.cognitive_engine.genai.Client") as MockClient:
        mock_instance = MockClient.return_value

        async def smart_parrot(model, contents, config=None):
            """
            A fake LLM that returns context-appropriate responses.
            """
            prompt = str(contents) if isinstance(contents, list) else contents
            response = MagicMock()

            # Scanner: Returns JSON list of entities
            if "SCANNER" in prompt or "proper nouns" in prompt.lower():
                response.text = '["The Iron Dominion", "Forgemaster Kael", "The Forge"]'

            # Outliner: Returns JSON blueprint
            elif "OUTLINER" in prompt or "JSON" in prompt:
                response.text = """{
                    "Title": "Test Entity",
                    "Type": "Faction",
                    "Simulation_Mode": "FULL",
                    "Sections": ["Overview", "Systems", "Details"]
                }"""

            # Classifier: Returns category key
            elif "Classify" in prompt:
                response.text = "Factions"

            # Creator: Returns Markdown content with dual-truth structure
            else:
                response.text = """# Generated Entity

## Overview
Mock content generated by the test harness.

## Game Master Notes
> [!secret] GM Truth
> This entity was created by the test suite to verify persona logic.
"""

            # Set usage_metadata to None to trigger fallback estimation in CognitiveEngine
            response.usage_metadata = None
            return response

        # Mock both sync and async methods
        mock_instance.aio.models.generate_content = AsyncMock(side_effect=smart_parrot)
        mock_instance.models.generate_content.side_effect = smart_parrot

        yield mock_instance


@pytest.fixture
def sample_state(mock_vault):
    """
    Returns a typical AgentState for testing graph nodes.
    """
    return {
        "current_file_path": str(mock_vault / "Source Files" / "Canon_Lore.md"),
        "sprawl_queue": [],
        "visited_entities": set(),
        "recursion_depth": 0,
        "root_dir": str(mock_vault),
        "generated_files": [],
        "latest_rag_count": 0,
        "vault_glossary": [],
        "world_primer": "Test world primer",
        "entity_outline": "{}",
        "current_entity_category": "03_Factions",
        "current_density_settings": ("TIER 1", 3500, "Full Simulation"),
        "simulation_mode": "FULL",
    }
